# Generated by Django 6.0.8 on 2026-08-06 14:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=150)),
                ('college_name', models.CharField(max_length=150)),
                ('link_valid_from', models.DateTimeField()),
                ('link_valid_until', models.DateTimeField()),
                ('logical_questions', models.SmallIntegerField(default=10)),
                ('quantitative_questions', models.SmallIntegerField(default=10)),
                ('verbal_questions', models.SmallIntegerField(default=10)),
                ('programming_questions', models.SmallIntegerField(default=10)),
                ('logical_cutoff', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('quantitative_cutoff', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('verbal_cutoff', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('programming_cutoff', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('exam_duration_minutes', models.SmallIntegerField(default=45)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=15)),
                ('total_candidates', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_code', models.CharField(help_text='e.g. user.view, user.create, user.edit', max_length=60, unique=True)),
                ('module', models.CharField(help_text='Grouping for UI: Users, Batches, Candidates, etc.', max_length=40)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['module', 'permission_code'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_code', models.CharField(help_text='Display code, e.g. Q-0181', max_length=20, unique=True)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500, null=True)),
                ('option_d', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('marks', models.SmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['question_code'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=60, unique=True)),
                ('section_key', models.CharField(help_text="e.g. 'logical', 'quantitative'", max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('min_required_active', models.SmallIntegerField(default=50, help_text='Question Bank Health threshold')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'question_bank_sections',
                'ordering': ['section_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_code', models.CharField(help_text="e.g. 'admin', 'ta'", max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.SmallIntegerField(default=0, help_text='Higher = more privileged')),
                ('is_system', models.BooleanField(default=True, help_text="System roles can't be deleted from UI")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['-priority', 'role_name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhaar_number', models.CharField(max_length=255)),
                ('college_name', models.CharField(blank=True, max_length=150, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passing_out_year', models.SmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_status', models.CharField(choices=[('ok', 'OK'), ('missing_email', 'Missing Email'), ('missing_aadhaar', 'Missing Aadhaar'), ('missing_name', 'Missing Name'), ('missing_college', 'Missing College')], default='ok', max_length=20)),
                ('status', models.CharField(choices=[('pending_invite', 'Pending Invite'), ('invited', 'Invited'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('no_show', 'No Show')], default='pending_invite', max_length=15)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail')], default='pending', max_length=10)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_link_token', models.CharField(max_length=64, unique=True)),
                ('email_status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('link_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('is_link_used', models.BooleanField(default=False)),
                ('link_expired_at', models.DateTimeField()),
                ('is_re_invite', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, to='api.candidate')),
            ],
            options={
                'db_table': 'invitations',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('attempt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aadhaar_capture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('face_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('face_match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_verified_at', models.DateTimeField(blank=True, null=True)),
                ('session_recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('terminated', 'Terminated')], default='in_progress', max_length=12)),
                ('termination_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('total_answered', models.SmallIntegerField(default=0)),
                ('total_correct', models.SmallIntegerField(default=0)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('logical_score', models.SmallIntegerField(blank=True, null=True)),
                ('quantitative_score', models.SmallIntegerField(blank=True, null=True)),
                ('verbal_score', models.SmallIntegerField(blank=True, null=True)),
                ('programming_score', models.SmallIntegerField(blank=True, null=True)),
                ('logical_cleared', models.BooleanField(blank=True, null=True)),
                ('quantitative_cleared', models.BooleanField(blank=True, null=True)),
                ('verbal_cleared', models.BooleanField(blank=True, null=True)),
                ('programming_cleared', models.BooleanField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, to='api.candidate')),
                ('invitation', models.ForeignKey(db_column='invitation_id', on_delete=django.db.models.deletion.CASCADE, to='api.invitation')),
            ],
            options={
                'db_table': 'exam_attempts',
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='e.g. session_start, tab_switch', max_length=40)),
                ('event_details', models.JSONField(blank=True, null=True)),
                ('is_violation', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('event_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(db_column='attempt_id', on_delete=django.db.models.deletion.CASCADE, to='api.examattempt')),
            ],
            options={
                'db_table': 'proctoring_events',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('selected_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('time_spent_seconds', models.SmallIntegerField(blank=True, null=True)),
                ('is_auto_saved', models.BooleanField(default=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(db_column='attempt_id', on_delete=django.db.models.deletion.CASCADE, to='api.examattempt')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, to='api.question')),
            ],
            options={
                'db_table': 'exam_answers',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.PROTECT, to='api.questionbanksection'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='api.role')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.CharField(max_length=255)),
                ('setting_group', models.CharField(help_text='exam_config, duplicate_check, etc.', max_length=40)),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('otp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('otp_code_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('PASSWORD_RESET', 'Password Reset')], default='PASSWORD_RESET', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'otp_verifications',
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='sent_by',
            field=models.ForeignKey(db_column='sent_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.CreateModel(
            name='DuplicateCheck',
            fields=[
                ('check_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_status', models.CharField(choices=[('new', 'New'), ('duplicate_cleared', 'Duplicate Cleared'), ('duplicate_within_window', 'Duplicate Within Window')], default='new', max_length=25)),
                ('existing_attempt_date', models.DateTimeField(blank=True, null=True)),
                ('cooling_off_months', models.SmallIntegerField(default=3)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_checks', to='api.candidate')),
                ('existing_candidate', models.ForeignKey(db_column='existing_candidate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_matches', to='api.candidate')),
                ('checked_by', models.ForeignKey(db_column='checked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'duplicate_checks',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to='api.user'),
        ),
        migrations.AddField(
            model_name='batch',
            name='primary_ta_user',
            field=models.ForeignKey(db_column='primary_ta_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='primary_batches', to='api.user'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(help_text='e.g. login, create, update, delete', max_length=40)),
                ('entity_type', models.CharField(help_text='user | batch | candidate | question | invitation', max_length=40)),
                ('entity_id', models.BigIntegerField(help_text='PK of affected row')),
                ('action_details', models.JSONField(blank=True, null=True)),
                ('requires_review', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by', models.ForeignKey(db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logs', to='api.user')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['candidate'], name='ix_attempts_candidate'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('invitation',), name='ux_attempts_invitation'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(fields=['attempt', 'event_timestamp'], name='ix_events_attempt'),
        ),
        migrations.AddConstraint(
            model_name='examanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='ux_answers_attempt_question'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='ux_users_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='ix_users_role_id'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('setting_key',), name='ux_settings_key'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['section', 'status', 'difficulty'], name='ix_questions_section_status'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'purpose', 'expires_at'], name='ix_otp_user_purpose'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['candidate', 'batch'], name='ix_invitations_candidate'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('unique_link_token',), name='ux_invitations_token'),
        ),
        migrations.AddIndex(
            model_name='duplicatecheck',
            index=models.Index(fields=['candidate'], name='ix_dupchecks_candidate'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['batch', 'status'], name='ix_candidates_batch_status'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['aadhaar_number'], name='ix_candidates_aadhaar'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='ix_candidates_email'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='ix_batches_status'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='ix_audit_entity'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['requires_review', 'reviewed_at'], name='ix_audit_review'),
        ),
    ]
