# Generated by Django 6.0.8 on 2026-08-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_revokedrefreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Tokens issued before this timestamp are treated as stale (see api/authentication.py and api/services/tokens.py).', null=True),
        ),
    ]
