# Generated by Django 6.0.8 on 2026-08-10 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_password_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistoryEntry',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='api.user')),
            ],
            options={
                'db_table': 'password_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ix_pwdhist_user_created')],
            },
        ),
    ]
