# Generated by Django 6.0.8 on 2026-08-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_passwordhistoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='upload_row_number',
            field=models.SmallIntegerField(blank=True, help_text='Original row # in the uploaded Excel file, for traceability during review.', null=True),
        ),
    ]
