# Generated by Django 6.0.8 on 2026-08-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_candidate_upload_row_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status'], name='ix_candidates_status'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['result'], name='ix_candidates_result'),
        ),
    ]
