# Generated by Django 6.0.8 on 2026-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_batch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatecheck',
            name='check_status',
            field=models.CharField(choices=[('new', 'New'), ('previously_invited', 'Invited Before - Not Attempted'), ('duplicate_cleared', 'Duplicate Cleared'), ('duplicate_within_window', 'Duplicate Within Window')], default='new', max_length=25),
        ),
    ]
