# Generated by Django 6.0.8 on 2026-08-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_duplicatecheck_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, help_text="Every problem found with this uploaded row: [{'field': 'Email', 'message': '...'}, ...]. Empty when the row is valid. Stored rather than recomputed so the review screen and the finalize check can never disagree about why a row was rejected."),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='validation_status',
            field=models.CharField(choices=[('ok', 'OK'), ('missing_email', 'Missing Email'), ('missing_aadhaar', 'Missing Aadhaar'), ('missing_name', 'Missing Name'), ('missing_college', 'Missing College'), ('invalid_email', 'Invalid Email'), ('duplicate_email', 'Duplicate Email'), ('invalid_aadhaar', 'Invalid Aadhaar'), ('invalid_mobile', 'Invalid Mobile')], default='ok', max_length=20),
        ),
    ]
