# Generated by Django 6.0.8 on 2026-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_candidate_validation_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='upload_raw',
            field=models.JSONField(blank=True, default=dict, help_text="Original spreadsheet text for fields whose model type can't hold a bad value: a Percentage cell reading 'abc' parses to NULL, making it indistinguishable from an empty cell, so 'must be a number' could never be reported. Keyed by field name, e.g. {'percentage': 'abc'}."),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='validation_status',
            field=models.CharField(choices=[('ok', 'OK'), ('missing_email', 'Missing Email'), ('missing_aadhaar', 'Missing Aadhaar'), ('missing_name', 'Missing Name'), ('missing_college', 'Missing College'), ('invalid_email', 'Invalid Email'), ('duplicate_email', 'Duplicate Email'), ('invalid_aadhaar', 'Invalid Aadhaar'), ('invalid_mobile', 'Invalid Mobile'), ('invalid_text', 'Invalid Text Field'), ('invalid_percentage', 'Invalid Percentage'), ('invalid_year', 'Invalid Passing Year')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='duplicatecheck',
            name='check_status',
            field=models.CharField(choices=[('new', 'New Candidate'), ('previously_invited', 'Invited Before - Not Attempted'), ('duplicate_cleared', 'Duplicate Found - Cleared'), ('duplicate_within_window', 'Duplicate Found - Within Window')], default='new', max_length=25),
        ),
    ]
