# Generated by Django 6.0.8 on 2026-08-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_candidate_upload_raw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='validation_status',
            field=models.CharField(choices=[('ok', 'OK'), ('missing_email', 'Missing Email'), ('missing_aadhaar', 'Missing Aadhaar'), ('missing_name', 'Missing Name'), ('missing_college', 'Missing College'), ('invalid_email', 'Invalid Email'), ('duplicate_email', 'Duplicate Email'), ('invalid_aadhaar', 'Invalid Aadhaar'), ('duplicate_aadhaar', 'Duplicate Aadhaar'), ('invalid_mobile', 'Invalid Mobile'), ('invalid_text', 'Invalid Text Field'), ('invalid_percentage', 'Invalid Percentage'), ('invalid_year', 'Invalid Passing Year')], default='ok', max_length=20),
        ),
    ]
