# Generated by Django 6.0.8 on 2026-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_candidate_validation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='validation_status',
            field=models.CharField(choices=[('ok', 'OK'), ('missing_email', 'Missing Email'), ('missing_aadhaar', 'Missing Aadhaar'), ('missing_name', 'Missing Name'), ('missing_college', 'Missing College'), ('invalid_email', 'Invalid Email'), ('duplicate_email', 'Duplicate Email'), ('invalid_aadhaar', 'Invalid Aadhaar'), ('duplicate_aadhaar', 'Duplicate Aadhaar'), ('invalid_mobile', 'Invalid Mobile'), ('invalid_text', 'Invalid Text Field'), ('invalid_percentage', 'Invalid Percentage'), ('invalid_year', 'Invalid Passing Year'), ('missing_mobile', 'Missing Mobile'), ('missing_degree', 'Missing Degree'), ('missing_stream', 'Missing Stream'), ('missing_percentage', 'Missing Percentage'), ('missing_year', 'Missing Passing Out Year'), ('missing_location', 'Missing Location')], default='ok', max_length=20),
        ),
    ]
