# Generated by Django 6.0.8 on 2026-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_candidate_aadhaar_last4'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email_error',
            field=models.TextField(blank=True, help_text='Error reported by the email service on the last failed attempt. Null when the last attempt succeeded.', null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='email_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
