# Generated by Django 6.0.8 on 2026-08-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_invitation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='link_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='link_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
