# Generated by Django 6.0.8 on 2026-08-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_batch_link_dates_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='college_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
