# Generated by Django 6.0.8 on 2026-08-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_batch_college_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10),
        ),
    ]
