# Generated by Django 6.0.8 on 2026-09-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_invitation_retry_count_alter_invitation_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
