# Generated by Django 6.0.8 on 2026-09-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_examanswer_marked_for_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatecheck',
            name='check_status',
            field=models.CharField(choices=[('new', 'New Candidate'), ('previously_invited', 'Invite Already Sent'), ('duplicate_cleared', 'Already Took the Exam - Cooling Period Completed'), ('duplicate_within_window', 'Already Took the Exam - Within Cooling Period')], default='new', max_length=25),
        ),
    ]
