# Generated by Django 6.0.8 on 2026-09-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_backfill_candidate_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='link_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
