# Generated by Django 6.0.8 on 2026-09-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_candidate_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='validation_status',
            field=models.CharField(choices=[('ok', 'OK'), ('missing_email', 'Missing Email'), ('missing_aadhaar', 'Missing Aadhaar Last 4 Digits'), ('missing_name', 'Missing Name'), ('missing_college', 'Missing College'), ('invalid_email', 'Invalid Email'), ('duplicate_email', 'Duplicate Email'), ('invalid_aadhaar', 'Invalid Aadhaar Last 4 Digits'), ('duplicate_aadhaar', 'Duplicate Aadhaar Last 4 Digits'), ('invalid_mobile', 'Invalid Mobile'), ('invalid_text', 'Invalid Text Field'), ('invalid_percentage', 'Invalid Percentage'), ('invalid_year', 'Invalid Passing Year'), ('missing_mobile', 'Missing Mobile'), ('missing_degree', 'Missing Degree'), ('missing_stream', 'Missing Stream'), ('missing_percentage', 'Missing Percentage'), ('missing_year', 'Missing Passing Out Year'), ('missing_location', 'Missing Location'), ('missing_dob', 'Missing Date of Birth'), ('invalid_dob', 'Invalid Date of Birth'), ('underage', 'Underage')], default='ok', max_length=20),
        ),
    ]
