# Generated by Django 6.0.8 on 2026-09-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_candidate_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='seb_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
