# Generated by Django 6.0.8 on 2026-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_examattempt_seb_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
