# Generated by Django 6.0.8 on 2026-09-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_examattempt_last_activity_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='mp4_transcode_attempts',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='session_recording_mp4_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
