# Generated by Django 6.0.8 on 2026-09-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_examattempt_mp4_transcode_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='ai_proctoring_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
