# Generated by Django 6.0.8 on 2026-09-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_batch_ai_proctoring_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='aadhaar_decoded_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='aadhaar_number_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='aadhaar_verification_attempts',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='aadhaar_verification_method',
            field=models.CharField(choices=[('none', 'Not Processed'), ('qr_legacy', 'Legacy Unsigned QR'), ('qr_secure', 'UIDAI Secure QR'), ('ocr', 'OCR Fallback')], default='none', max_length=9),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='aadhaar_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('match', 'Matches Aadhaar Last 4'), ('mismatch', 'Does Not Match Aadhaar Last 4'), ('unreadable', 'Could Not Be Read'), ('signature_invalid', 'QR Signature Failed Verification')], default='pending', max_length=17),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='aadhaar_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['aadhaar_number_hash'], name='ix_attempts_aadhaar_hash'),
        ),
    ]
