# Generated by Django 6.0.8 on 2026-09-18 07:01
#
# Marks-weighted scoring - see services/exam_session._grade_sections for why.

from django.db import migrations, models
from django.db.models import Q, Sum


def backfill_marks(apps, schema_editor):
    """Fill the two new columns for attempts that were already graded.

    Without this every completed candidate reads as "0/40" the moment the UI starts showing
    total_marks_earned, because the column defaults to 0 and nothing else writes it until that
    attempt happens to be re-graded. The numbers are computed from each attempt's OWN answers
    rather than copied from total_correct, so they stay correct even if a weighted question was
    somehow already in play.

    Irreversible in the sense that matters: reversing just drops the columns, and these values
    are derived, never authoritative - _grade_sections recomputes them from the same answers.
    """
    ExamAttempt = apps.get_model('api', 'ExamAttempt')
    ExamAnswer = apps.get_model('api', 'ExamAnswer')

    totals = {
        row['attempt_id']: (row['earned'] or 0, row['available'] or 0)
        for row in ExamAnswer.objects.values('attempt_id').annotate(
            available=Sum('question__marks'),
            earned=Sum('question__marks', filter=Q(is_correct=True)),
        )
    }
    if not totals:
        return

    updates = []
    for attempt in ExamAttempt.objects.filter(attempt_id__in=totals).only(
        'attempt_id', 'total_marks_earned', 'total_marks',
    ):
        attempt.total_marks_earned, attempt.total_marks = totals[attempt.attempt_id]
        updates.append(attempt)
    ExamAttempt.objects.bulk_update(
        updates, ['total_marks_earned', 'total_marks'], batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_examattempt_aadhaar_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='total_marks',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_marks_earned',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.RunPython(backfill_marks, migrations.RunPython.noop),
    ]
