# Generated by Django 6.0.8 on 2026-09-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_examattempt_marks_weighted_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='aadhaar_verification_method',
            field=models.CharField(choices=[('none', 'Not Processed'), ('qr_legacy', 'Legacy Unsigned QR'), ('qr_secure', 'UIDAI Secure QR'), ('ocr', 'OCR Fallback'), ('ocr_masked', 'OCR (Masked Card)')], default='none', max_length=12),
        ),
    ]
