# Generated by Django 6.0.8 on 2026-09-21 09:58
#
# Sections become data instead of columns. Adds BatchSection/AttemptSectionScore and moves every
# existing batch's and attempt's per-section values into them.

import django.db.models.deletion
from django.db import migrations, models

# The four original sections, in the order candidates have always sat them. Inlined rather than
# imported from api.services.question_selection: migrations must not depend on application code
# that can change shape later and silently break this historical step - and this one is about to
# stop being a constant there at all.
ORIGINAL_SECTION_ORDER = ['logical', 'quantitative', 'verbal', 'programming']


def order_original_sections(apps, schema_editor):
    """Give the four original sections the display_order they have always been shown in.

    Every section starts at display_order=100, so without this the order becomes alphabetical
    (logical, programming, quantitative, verbal) the moment ordering switches to it - silently
    reordering the sections of every exam in flight. A section added later keeps the 100 default
    and therefore sorts after these four, which is where a new section belongs by default.
    """
    QuestionBankSection = apps.get_model('api', 'QuestionBankSection')
    for index, section_key in enumerate(ORIGINAL_SECTION_ORDER):
        QuestionBankSection.objects.filter(section_key=section_key).update(display_order=index)


def backfill_sections(apps, schema_editor):
    """Move every batch's question counts/cutoffs and every attempt's scores/cleared flags out of
    their hardcoded columns and into rows.

    A batch gets a BatchSection for a section only when it configured MORE THAN ZERO questions
    for it: the columns could not express "this batch does not use programming" except as a zero,
    and carrying that zero forward as a real row would show an empty section in the new
    section-picker UI as if it had been chosen.

    An attempt gets an AttemptSectionScore for each of its batch's sections. total_marks is
    recovered from the attempt's own ExamAnswer rows rather than assumed equal to the question
    count - the two differ as soon as a question is worth more than 1 mark, and the denominator
    is what the Section-wise Result table renders the score over.
    """
    Batch = apps.get_model('api', 'Batch')
    BatchSection = apps.get_model('api', 'BatchSection')
    ExamAttempt = apps.get_model('api', 'ExamAttempt')
    ExamAnswer = apps.get_model('api', 'ExamAnswer')
    AttemptSectionScore = apps.get_model('api', 'AttemptSectionScore')
    QuestionBankSection = apps.get_model('api', 'QuestionBankSection')

    sections = {s.section_key: s for s in QuestionBankSection.objects.all()}
    if not sections:
        return  # a fresh database with no seed data yet - nothing to move

    batch_rows = []
    for batch in Batch.objects.all().iterator():
        for section_key in ORIGINAL_SECTION_ORDER:
            section = sections.get(section_key)
            count = getattr(batch, f'{section_key}_questions', 0) or 0
            if section is None or count <= 0:
                continue
            batch_rows.append(BatchSection(
                batch_id=batch.batch_id, section_id=section.section_id,
                question_count=count, cutoff=getattr(batch, f'{section_key}_cutoff'),
            ))
    BatchSection.objects.bulk_create(batch_rows, batch_size=500, ignore_conflicts=True)

    # Marks available per (attempt, section), straight from the papers that were actually sat.
    marks_by_attempt_section = {}
    for row in ExamAnswer.objects.values(
        'attempt_id', 'question__section_id',
    ).annotate(total=models.Sum('question__marks')):
        marks_by_attempt_section[(row['attempt_id'], row['question__section_id'])] = (
            row['total'] or 0
        )

    counts_by_batch = {}
    for row in BatchSection.objects.values('batch_id', 'section_id'):
        counts_by_batch.setdefault(row['batch_id'], []).append(row['section_id'])
    section_key_by_id = {s.section_id: key for key, s in sections.items()}

    score_rows = []
    for attempt in ExamAttempt.objects.select_related('invitation').iterator():
        for section_id in counts_by_batch.get(attempt.invitation.batch_id, []):
            section_key = section_key_by_id.get(section_id)
            if section_key is None:
                continue
            score_rows.append(AttemptSectionScore(
                attempt_id=attempt.attempt_id, section_id=section_id,
                score=getattr(attempt, f'{section_key}_score', None) or 0,
                total_marks=marks_by_attempt_section.get(
                    (attempt.attempt_id, section_id), 0),
                cleared=getattr(attempt, f'{section_key}_cleared', None),
            ))
    AttemptSectionScore.objects.bulk_create(score_rows, batch_size=500, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_relink_stale_candidate_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbanksection',
            options={'ordering': ['display_order', 'section_name']},
        ),
        migrations.AddField(
            model_name='questionbanksection',
            name='display_order',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='questionbanksection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AttemptSectionScore',
            fields=[
                ('attempt_section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.SmallIntegerField(default=0)),
                ('total_marks', models.SmallIntegerField(default=0)),
                ('cleared', models.BooleanField(blank=True, null=True)),
                ('attempt', models.ForeignKey(db_column='attempt_id', on_delete=django.db.models.deletion.CASCADE, related_name='section_scores', to='api.examattempt')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.PROTECT, to='api.questionbanksection')),
            ],
            options={
                'db_table': 'attempt_section_scores',
                'ordering': ['section__display_order', 'section__section_name'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'section'), name='ux_attempt_sections_attempt_section')],
            },
        ),
        migrations.CreateModel(
            name='BatchSection',
            fields=[
                ('batch_section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_count', models.SmallIntegerField(default=10)),
                ('cutoff', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.batch')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.PROTECT, related_name='batch_sections', to='api.questionbanksection')),
            ],
            options={
                'db_table': 'batch_sections',
                'ordering': ['section__display_order', 'section__section_name'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'section'), name='ux_batch_sections_batch_section')],
            },
        ),
        # Ordering first: backfill reads it, and every downstream read depends on the four
        # original sections keeping the sequence candidates have always sat them in.
        migrations.RunPython(order_original_sections, migrations.RunPython.noop),
        # Reverse is a no-op rather than a delete: reversing this migration drops both tables
        # anyway, and the rows are derived - re-running the forward step rebuilds them exactly.
        migrations.RunPython(backfill_sections, migrations.RunPython.noop),
    ]
