# Generated by Django 6.0.8 on 2026-09-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_dynamic_exam_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Blocks staff endpoints until the holder sets their own password. Cleared by any successful password change or reset.'),
        ),
    ]
