# Generated by Django 6.0.8 on 2026-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='setting_value',
            field=models.TextField(),
        ),
    ]
