# Generated by Django 6.0.8 on 2026-10-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_setting_value_textfield'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'last_activity_at'], name='ix_attempts_status_activity'),
        ),
    ]
