"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# No insecure fallback outside DEBUG - this key also signs JWTs (see SIMPLE_JWT below),
# so silently running with a well-known default would let anyone forge tokens.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-do-not-use-in-production'
    else:
        raise ImproperlyConfigured('SECRET_KEY environment variable is required when DEBUG=False.')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

# django.contrib.admin is deliberately NOT installed and /admin/ is not routed. Every model
# was registered there with no write protection, which made it a full bypass of this app's own
# RBAC (api/permissions.py): editable AuditLog rows, readable Question.correct_option, and a
# login path with none of the rate limiting or lockout the real login has. Admin also
# authenticates against django.contrib.auth.User - a different user table from the one this app
# uses - so a single createsuperuser would have created an account outside the RBAC entirely.
# django.contrib.auth stays: it supplies the password hashers and validators the app relies on.
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'anymail',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files in production. Django itself serves nothing when
    # DEBUG=False, and this app is deployed without a separate web server in front of it doing
    # static duty, so without WhiteNoise every /static/ URL 404s. Must sit directly after
    # SecurityMiddleware, per WhiteNoise's documented ordering requirement.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            # Defaults to require: this app's Postgres is a managed cloud instance reached
            # over the network, and an unencrypted connection there would put the database
            # password and every candidate record on the wire in clear text. A local Postgres
            # without TLS configured needs DB_SSLMODE=disable set explicitly in .env.
            'sslmode': os.environ.get('DB_SSLMODE', 'require'),
        },
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', 0)),
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Replaces MinimumLengthValidator - enforces its own, stricter length plus
        # a mix of character classes (upper/lower/digit/special).
        'NAME': 'api.validators.ComplexityValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# How many of a user's most recent passwords (in addition to their current one) they
# cannot reuse when changing/resetting their password. See api/services/passwords.py.
PASSWORD_HISTORY_COUNT = int(os.environ.get('PASSWORD_HISTORY_COUNT', 5))


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# Timezone that candidate-facing text is rendered in. Storage stays UTC (above) - this is a
# presentation choice only. Emails have to state a wall-clock time the candidate can act on,
# and the browser isn't there to localize it the way the staff UI does, so the conversion has
# to happen server-side and the zone has to be named in the text (see
# services/email_templates.format_datetime).
DISPLAY_TIME_ZONE = os.environ.get('DISPLAY_TIME_ZONE', 'Asia/Kolkata')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# collectstatic's destination. Without this, `manage.py collectstatic` raises
# ImproperlyConfigured and any deployment step that runs it fails outright. Already gitignored.
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Extra directory of app-owned static files, if present (templates/ has a sibling static/).
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').is_dir() else []

# Built React SPA, served from this same origin - see config/spa.py for why the frontend and
# API must not be split across hostnames. The deployment pipeline copies Frontend/dist/ here.
# Absent in a local checkout, where Vite's dev server serves the frontend on :5173 instead.
FRONTEND_DIST = BASE_DIR / 'frontend'
if FRONTEND_DIST.is_dir():
    # Lets WhiteNoise's middleware serve the SPA's own files (/assets/*, favicon.svg) before the
    # URL resolver runs, so the catch-all in urls.py only ever sees real client-side routes.
    # WHITENOISE_INDEX_FILE is deliberately left off: index.html must go through the
    # never_cache view instead of WhiteNoise's own caching headers.
    WHITENOISE_ROOT = FRONTEND_DIST
    # Vite fingerprints everything it emits into /assets/, so those can be cached forever - a
    # changed file gets a new name, so a stale entry is never served for new content. Needed
    # explicitly because WhiteNoise only recognises hashed filenames under STATIC_URL, and would
    # otherwise fall back to a 60-second max-age and revalidate the whole bundle on every load.
    # nginx.conf applies the same rule to /assets/ for the Docker stack.
    WHITENOISE_IMMUTABLE_FILE_TEST = r'^/assets/'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compresses and fingerprints collected files so they can be cached hard. The
        # non-manifest variant is used deliberately: ManifestStaticFilesStorage raises at
        # request time for any file missing from the manifest, which turns a cosmetic asset
        # typo into a 500. Nothing here needs cache-busting badly enough to accept that.
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS
# The refresh token rides in an httpOnly cookie, so the frontend origin must be
# explicitly allowed (not wildcarded) and credentials must be permitted.
FRONTEND_ORIGIN = os.environ.get('FRONTEND_ORIGIN', 'http://localhost:5173')
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [FRONTEND_ORIGIN]
CORS_ALLOW_CREDENTIALS = True

# DRF Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.CustomJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # Without this, an exception DRF doesn't recognise escapes to Django and the client gets an
    # HTML error page. Every caller here is an axios client that does res.data.detail, so an
    # HTML body surfaces as an unreadable error in the UI and the real cause is lost.
    'EXCEPTION_HANDLER': 'api.exception_handler.api_exception_handler',
}

# djangorestframework-simplejwt
# NOTE: rest_framework_simplejwt.token_blacklist is intentionally NOT installed -
# its OutstandingToken/BlacklistedToken models FK to AUTH_USER_MODEL (django.contrib.auth.User),
# which is not the model we authenticate with (see api/authentication.py). Refresh-token
# revocation on logout is handled by our own RevokedRefreshToken model (api/models/auth_token.py),
# checked manually in the /api/auth/refresh/ view.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
}

# Auth / OTP
# Comma-separated list - lets you temporarily allow a personal test-account domain
# (e.g. for email-deliverability testing) alongside the real corporate domain.
CORPORATE_EMAIL_DOMAINS = [
    d.strip().lower()
    for d in os.environ.get('CORPORATE_EMAIL_DOMAIN', 'accelirate.com').split(',')
    if d.strip()
]
OTP_EXPIRY_MINUTES = int(os.environ.get('OTP_EXPIRY_MINUTES', 10))
OTP_RESEND_COOLDOWN_SECONDS = int(os.environ.get('OTP_RESEND_COOLDOWN_SECONDS', 60))

# Refresh token cookie
REFRESH_COOKIE_NAME = 'refresh_token'
REFRESH_COOKIE_PATH = '/api/auth/'
# Strict is right when the frontend and the API share a registrable domain (the intended
# deployment: app.example.com + api.example.com are same-site). If they end up on genuinely
# different sites - say a *.azurestaticapps.net frontend calling a *.azurewebsites.net API -
# the browser silently withholds this cookie on every refresh call and users get logged out
# mid-session with no error anywhere. That case needs 'None', which browsers only honour on a
# Secure cookie, so it cannot be used over plain HTTP.
REFRESH_COOKIE_SAMESITE = os.environ.get('REFRESH_COOKIE_SAMESITE', 'Strict')

# Email - Microsoft Graph (app-only). Sending from inside the M365 tenant avoids the
# external-sender quarantine that held @accelirate.com invites when this went via SendGrid.
# EMAIL_BACKEND stays overridable so a deployment can fall back to SendGrid or to the console
# backend for local work without a code change.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'api.services.graph_email.GraphEmailBackend')

GRAPH_TENANT_ID = os.environ.get('GRAPH_TENANT_ID', '')
GRAPH_CLIENT_ID = os.environ.get('GRAPH_CLIENT_ID', '')
GRAPH_CLIENT_SECRET = os.environ.get('GRAPH_CLIENT_SECRET', '')
# Certificate-based app auth (private_key_jwt), an alternative to the client secret above -
# Microsoft's recommended stronger option for app-only Graph access. Both GRAPH_CERT_PATH (a PEM
# file holding the private key) and GRAPH_CERT_THUMBPRINT (the SHA-1 thumbprint Azure shows once
# the matching public certificate is uploaded to the app registration) must be set to activate
# it; graph_email.py falls back to GRAPH_CLIENT_SECRET whenever either is blank, so leaving these
# unset is always safe. See Backend/api/management/commands/generate_graph_cert.py to produce
# the key pair and get the exact values to paste here and into the Azure Portal.
GRAPH_CERT_PATH = os.environ.get('GRAPH_CERT_PATH', '')
GRAPH_CERT_THUMBPRINT = os.environ.get('GRAPH_CERT_THUMBPRINT', '')
# Mailbox the app sends as. Must be a real mailbox in the tenant that the app registration is
# permitted to send on behalf of.
GRAPH_SENDER = os.environ.get('GRAPH_SENDER', '')
# Keeping a copy of every candidate invite in the service mailbox is rarely wanted.
GRAPH_SAVE_TO_SENT_ITEMS = os.environ.get('GRAPH_SAVE_TO_SENT_ITEMS', 'false').lower() == 'true'

# Deliberate pacing between invitation emails, applied by management/commands/
# process_email_queue.py - the queue worker that sends every one of them - not Graph's own rate
# limit, it's the RECEIVING mail systems reading a burst of 100+ near-identical emails as
# bulk/spam activity. A small gap between sends is cheap insurance against that, without
# meaningfully slowing a real batch (100 candidates at the default adds under 3 minutes total).
INVITE_SEND_DELAY_SECONDS = float(os.environ.get('INVITE_SEND_DELAY_SECONDS', '1.5'))

# How many automatic retry-sweep attempts a stalled/failed invitation gets before the sweep
# stops touching it and it needs a deliberate manual resend. Without a ceiling, a permanently
# bad address (typo, mailbox doesn't exist) would be re-attempted by every scheduled run forever.
INVITE_MAX_RETRY_ATTEMPTS = int(os.environ.get('INVITE_MAX_RETRY_ATTEMPTS', '5'))

# Retained so EMAIL_BACKEND can be pointed back at SendGrid if Graph is unavailable.
ANYMAIL = {
    'SENDGRID_API_KEY': os.environ.get('SENDGRID_API_KEY', ''),
}
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@accelirate.com')

# Address candidates are told to contact for help with the assessment. Printed in the
# invitation email, so it must be a monitored mailbox - DEFAULT_FROM_EMAIL is a noreply
# address and is only the fallback so the invite never goes out with a blank contact.
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', '')

# Azure Blob Storage - proctoring evidence for the candidate exam-taking portal (identity
# photos, continuous session recording). See api/services/blob_storage.py. Left unset while
# DEBUG=True falls back to local disk (MEDIA_ROOT below) so the exam flow is testable without
# real Azure credentials; left unset with DEBUG=False raises clearly at first use instead of
# silently no-op'ing, since a missing evidence upload would otherwise fail invisibly mid-exam.
AZURE_STORAGE_CONNECTION_STRING = os.environ.get('AZURE_STORAGE_CONNECTION_STRING', '')
AZURE_STORAGE_CONTAINER_EVIDENCE = os.environ.get('AZURE_STORAGE_CONTAINER_EVIDENCE', 'proctoring-evidence')

# Local-disk fallback for the above, DEBUG-only (see api/services/blob_storage.py). Not used at
# all once AZURE_STORAGE_CONNECTION_STRING is set, and never reachable with DEBUG=False.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Base URL the local-disk fallback stamps onto evidence URLs it returns - CandidateEvidenceZipView
# fetches those URLs with a plain urllib.request.urlopen(), which needs an absolute URL, not a
# relative /media/... path. Only matters for this DEBUG-only fallback; production always goes
# through the real Azure SAS URLs instead.
LOCAL_MEDIA_BASE_URL = os.environ.get('LOCAL_MEDIA_BASE_URL', 'http://127.0.0.1:8000')

# Request body / file upload size caps. BatchUploadView additionally enforces its own tighter
# 5MB limit on the candidate spreadsheet specifically (see MAX_UPLOAD_SIZE_BYTES) - these are the
# app-wide backstop so no endpoint can be made to buffer an unbounded request body into memory.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Production transport/cookie hardening - gated so local dev (DEBUG=True) is unaffected.
# SESSION_COOKIE_SECURE/CSRF_COOKIE_SECURE are safe to force on whenever DEBUG is off (they just
# mark those cookies HTTPS-only, same idea as the refresh-token cookie's own secure flag - see
# _set_refresh_cookie in api/views/auth.py). SECURE_SSL_REDIRECT/HSTS are opt-in via their own
# env var instead of tied to DEBUG, because forcing an HTTPS redirect is only correct if THIS
# process terminates TLS - if it instead sits behind a reverse proxy/load balancer that
# terminates TLS and forwards plain HTTP, turning this on causes an infinite redirect loop
# unless SECURE_PROXY_SSL_HEADER is also configured to match that proxy. Set
# ENABLE_SSL_REDIRECT=True only once that's confirmed for your deployment.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = os.environ.get('ENABLE_SSL_REDIRECT', 'False') == 'True'
SECURE_HSTS_SECONDS = 31536000 if SECURE_SSL_REDIRECT else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_SSL_REDIRECT
SECURE_HSTS_PRELOAD = SECURE_SSL_REDIRECT

# Client IP resolution (used for rate-limit keys and audit logs).
# Only trust X-Forwarded-For if this app sits behind a proxy that YOU control and that
# overwrites/strips any client-supplied XFF header - otherwise an attacker can spoof this
# header to fake their source IP and bypass rate limiting entirely. Defaults to REMOTE_ADDR.
TRUST_X_FORWARDED_FOR = os.environ.get('TRUST_X_FORWARDED_FOR', 'False') == 'True'

# Tied to the same flag: behind a TLS-terminating proxy, Django sees plain HTTP and would
# otherwise consider every request insecure - which breaks SECURE_SSL_REDIRECT (infinite
# redirect loop) and request.is_secure(). Only meaningful when the proxy is trusted, which is
# exactly what TRUST_X_FORWARDED_FOR asserts, so it is deliberately not a separate switch.
if TRUST_X_FORWARDED_FOR:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cache - backs django-ratelimit counters and the login-lockout counter. LocMemCache (the
# Django default used when CACHES isn't set) is per-process, so in a multi-worker production
# deployment each worker would rate-limit independently, undermining both. Set REDIS_URL to
# share counters across workers (the `redis` package is already a pinned dependency).
REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
# Logging.
# Django's default configuration only attaches a console handler when DEBUG=True, and never
# configures the root logger at all. The practical effect with DEBUG=False was that every
# logger.info() in this codebase was discarded outright (the effective level fell back to
# WARNING), and logger.exception() output went to logging's lastResort handler - bare stderr,
# no timestamp, no logger name. That included the audit line recording which draft batches were
# deleted, which is the only record that a deletion happened at all.
#
# Everything goes to stdout/stderr rather than a file on purpose: the process runs in a
# container where the platform collects the streams, and a file inside the container would be
# lost on every restart and invisible to log aggregation.
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO')

LOGGING = {
    'version': 1,
    # Django's own default loggers are left in place rather than replaced.
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        # Catches anything without a more specific logger, so a stray library warning is not
        # silently dropped the way it was before.
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'api': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            # False, or every api.* record is emitted twice - once here and once at the root.
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            # Unhandled exceptions in a view. ERROR so a 500 is always visible even if
            # LOG_LEVEL is raised to quiet the app's own chatter.
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            # Every SQL statement, only when explicitly asked for. Left off by default because
            # it is enormous and echoes query parameters, which here include candidate PII.
            'handlers': ['console'],
            'level': os.environ.get('SQL_LOG_LEVEL', 'WARNING'),
            'propagate': False,
        },
    },
}

# Error reporting (optional). sentry-sdk was already a pinned dependency but nothing ever
# initialised it, so it reported nothing. Enabled only when SENTRY_DSN is set, which keeps
# local development and CI from sending events anywhere.
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'local'),
        # Traces are off by default: this is an error reporter, and performance sampling on a
        # low-traffic internal tool costs quota without telling anyone much.
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0')),
        # send_default_pii would attach request bodies, headers and cookies to every event.
        # Those carry candidate PII, JWTs and the refresh cookie, none of which should leave
        # the tenant to a third-party service.
        send_default_pii=False,
    )
