"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# No insecure fallback outside DEBUG - this key also signs JWTs (see SIMPLE_JWT below),
# so silently running with a well-known default would let anyone forge tokens.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-do-not-use-in-production'
    else:
        raise ImproperlyConfigured('SECRET_KEY environment variable is required when DEBUG=False.')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'anymail',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': os.environ.get('DB_SSLMODE', 'disable'),
        },
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', 0)),
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Replaces MinimumLengthValidator - enforces its own, stricter length plus
        # a mix of character classes (upper/lower/digit/special).
        'NAME': 'api.validators.ComplexityValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# How many of a user's most recent passwords (in addition to their current one) they
# cannot reuse when changing/resetting their password. See api/services/passwords.py.
PASSWORD_HISTORY_COUNT = int(os.environ.get('PASSWORD_HISTORY_COUNT', 5))


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS
# The refresh token rides in an httpOnly cookie, so the frontend origin must be
# explicitly allowed (not wildcarded) and credentials must be permitted.
FRONTEND_ORIGIN = os.environ.get('FRONTEND_ORIGIN', 'http://localhost:5173')
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [FRONTEND_ORIGIN]
CORS_ALLOW_CREDENTIALS = True

# DRF Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.CustomJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# djangorestframework-simplejwt
# NOTE: rest_framework_simplejwt.token_blacklist is intentionally NOT installed -
# its OutstandingToken/BlacklistedToken models FK to AUTH_USER_MODEL (django.contrib.auth.User),
# which is not the model we authenticate with (see api/authentication.py). Refresh-token
# revocation on logout is handled by our own RevokedRefreshToken model (api/models/auth_token.py),
# checked manually in the /api/auth/refresh/ view.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
}

# Auth / OTP
# Comma-separated list - lets you temporarily allow a personal test-account domain
# (e.g. for email-deliverability testing) alongside the real corporate domain.
CORPORATE_EMAIL_DOMAINS = [
    d.strip().lower()
    for d in os.environ.get('CORPORATE_EMAIL_DOMAIN', 'accelirate.com').split(',')
    if d.strip()
]
OTP_EXPIRY_MINUTES = int(os.environ.get('OTP_EXPIRY_MINUTES', 10))
OTP_RESEND_COOLDOWN_SECONDS = int(os.environ.get('OTP_RESEND_COOLDOWN_SECONDS', 60))

# Refresh token cookie
REFRESH_COOKIE_NAME = 'refresh_token'
REFRESH_COOKIE_PATH = '/api/auth/'

# Email - Microsoft Graph (app-only). Sending from inside the M365 tenant avoids the
# external-sender quarantine that held @accelirate.com invites when this went via SendGrid.
# EMAIL_BACKEND stays overridable so a deployment can fall back to SendGrid or to the console
# backend for local work without a code change.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'api.services.graph_email.GraphEmailBackend')

GRAPH_TENANT_ID = os.environ.get('GRAPH_TENANT_ID', '')
GRAPH_CLIENT_ID = os.environ.get('GRAPH_CLIENT_ID', '')
GRAPH_CLIENT_SECRET = os.environ.get('GRAPH_CLIENT_SECRET', '')
# Mailbox the app sends as. Must be a real mailbox in the tenant that the app registration is
# permitted to send on behalf of.
GRAPH_SENDER = os.environ.get('GRAPH_SENDER', '')
# Keeping a copy of every candidate invite in the service mailbox is rarely wanted.
GRAPH_SAVE_TO_SENT_ITEMS = os.environ.get('GRAPH_SAVE_TO_SENT_ITEMS', 'false').lower() == 'true'

# Retained so EMAIL_BACKEND can be pointed back at SendGrid if Graph is unavailable.
ANYMAIL = {
    'SENDGRID_API_KEY': os.environ.get('SENDGRID_API_KEY', ''),
}
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@accelirate.com')

# Address candidates are told to contact for help with the assessment. Printed in the
# invitation email, so it must be a monitored mailbox - DEFAULT_FROM_EMAIL is a noreply
# address and is only the fallback so the invite never goes out with a blank contact.
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', '')

# Azure Blob Storage - proctoring evidence for the candidate exam-taking portal (identity
# photos, continuous session recording). See api/services/blob_storage.py. Left unset while
# DEBUG=True falls back to local disk (MEDIA_ROOT below) so the exam flow is testable without
# real Azure credentials; left unset with DEBUG=False raises clearly at first use instead of
# silently no-op'ing, since a missing evidence upload would otherwise fail invisibly mid-exam.
AZURE_STORAGE_CONNECTION_STRING = os.environ.get('AZURE_STORAGE_CONNECTION_STRING', '')
AZURE_STORAGE_CONTAINER_EVIDENCE = os.environ.get('AZURE_STORAGE_CONTAINER_EVIDENCE', 'proctoring-evidence')

# Local-disk fallback for the above, DEBUG-only (see api/services/blob_storage.py). Not used at
# all once AZURE_STORAGE_CONNECTION_STRING is set, and never reachable with DEBUG=False.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Base URL the local-disk fallback stamps onto evidence URLs it returns - CandidateEvidenceZipView
# fetches those URLs with a plain urllib.request.urlopen(), which needs an absolute URL, not a
# relative /media/... path. Only matters for this DEBUG-only fallback; production always goes
# through the real Azure SAS URLs instead.
LOCAL_MEDIA_BASE_URL = os.environ.get('LOCAL_MEDIA_BASE_URL', 'http://127.0.0.1:8000')

# Request body / file upload size caps. BatchUploadView additionally enforces its own tighter
# 5MB limit on the candidate spreadsheet specifically (see MAX_UPLOAD_SIZE_BYTES) - these are the
# app-wide backstop so no endpoint can be made to buffer an unbounded request body into memory.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Production transport/cookie hardening - gated so local dev (DEBUG=True) is unaffected.
# SESSION_COOKIE_SECURE/CSRF_COOKIE_SECURE are safe to force on whenever DEBUG is off (they just
# mark those cookies HTTPS-only, same idea as the refresh-token cookie's own secure flag - see
# _set_refresh_cookie in api/views/auth.py). SECURE_SSL_REDIRECT/HSTS are opt-in via their own
# env var instead of tied to DEBUG, because forcing an HTTPS redirect is only correct if THIS
# process terminates TLS - if it instead sits behind a reverse proxy/load balancer that
# terminates TLS and forwards plain HTTP, turning this on causes an infinite redirect loop
# unless SECURE_PROXY_SSL_HEADER is also configured to match that proxy. Set
# ENABLE_SSL_REDIRECT=True only once that's confirmed for your deployment.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = os.environ.get('ENABLE_SSL_REDIRECT', 'False') == 'True'
SECURE_HSTS_SECONDS = 31536000 if SECURE_SSL_REDIRECT else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_SSL_REDIRECT
SECURE_HSTS_PRELOAD = SECURE_SSL_REDIRECT

# Client IP resolution (used for rate-limit keys and audit logs).
# Only trust X-Forwarded-For if this app sits behind a proxy that YOU control and that
# overwrites/strips any client-supplied XFF header - otherwise an attacker can spoof this
# header to fake their source IP and bypass rate limiting entirely. Defaults to REMOTE_ADDR.
TRUST_X_FORWARDED_FOR = os.environ.get('TRUST_X_FORWARDED_FOR', 'False') == 'True'

# Cache - backs django-ratelimit counters and the login-lockout counter. LocMemCache (the
# Django default used when CACHES isn't set) is per-process, so in a multi-worker production
# deployment each worker would rate-limit independently, undermining both. Set REDIS_URL to
# share counters across workers (the `redis` package is already a pinned dependency).
REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }